@startuml
title Domain Model
class HourAdjustment
class Invoice
class RectifyingInvoice
class InvoiceManager
class Notification
class Employee{
- alias
- bizneoAlias
- joinDate
- leaveDate
- hourReporting(?startDate, ?endDate, ?project)
}
class Hosting{
- title
- description
- periodicity
- fee
}
class Project{
- title
- descriptionT
- fee
- deadline
}
class PurchaseOrder{
- number
- startDate
- totalHours
remainingHours()
}
class Entry{
- day
- hours
- description
}
class HourAdjustment{
- day
- description
- hours
}
class EntryGroup{
- title
- hoursBudget
- fee
- deadline
- remainingHours()
}
class Invoice {
- date
- base
- tax
- status
- total()
}
class Company{
- cif
}
class DaysOff{
- day
}
class Invoices <<Excel>> {
- startDate
- endDate
}
class User {
- email
- password
}
User <|-- Employee
User <|-- ExternalReviewer
User <|-- InvoiceManager
User <-up- “n” Notification
Client o-- “n” Company
Project o-- ExternalReviewer
Project o-- “n” EntryGroup
Project o-- “n” PurchaseOrder
EntryGroup o-- “n” Entry
EntryGroup o-- “n” HourAdjustment
Invoices  *-- “n” Invoice
InvoiceManager -- “n” Invoices
InvoiceManager -- “n” HourAdjustment
Company o-- “n” Project
Company o-- “n” Hosting
Project *-- Entry
Project *-- HourAdjustment
Project “0-1" o-- “n” Invoice
Employee <-- “n” Entry
Invoice <|-- RectifyingInvoice
Invoice <|-- StandardInvoice
StandardInvoice "n"<-- RectifyingInvoice
Invoice “n” --o “1" PurchaseOrder
Invoice “n” --o “0-1" Hosting
Employee *-- DaysOff
@enduml